name: Secret Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret-detection:
    name: Secret Detection Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for comprehensive scanning
    
    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified
    
    - name: Run GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
    
    - name: Run Semgrep Secret Detection
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/nodejs
          p/typescript
        generateSarif: "1"
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    
    - name: Upload Semgrep Results to GitHub
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('semgrep.sarif') != ''
      with:
        sarif_file: semgrep.sarif
    
    - name: Create Security Summary
      if: always()
      run: |
        echo "## 🔒 Secret Detection Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Tools Used:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ TruffleHog: Deep git history scanning" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ GitLeaks: Pattern-based secret detection" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Semgrep: Custom security rules" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Results:" >> $GITHUB_STEP_SUMMARY
        if [ "${{ job.status }}" == "success" ]; then
          echo "🟢 No secrets detected in codebase" >> $GITHUB_STEP_SUMMARY
        else
          echo "🔴 Potential secrets found - Check workflow logs for details" >> $GITHUB_STEP_SUMMARY
        fi